### ISSUE TITLE
Problem with Imgur embeds

### ISSUE THREAD

**Issue by Flyingtoast** [Fiddlekins/SpookyX#11]
It seems when an OP post ends with a link to an imgur album, every single post in the thread will have the first image of that album embedded in it. I noticed the problem here in an archived Bloodborne General.
![spookyx issue](https://cloud.githubusercontent.com/assets/9301153/18535414/0092c866-7ac2-11e6-98d9-78c4cb894982.png)

**Comment by Fiddlekins** [comment]
Ah bugger. Can you link me to the problem page please?

**Comment by Fiddlekins** [comment]
Nevermind, image had the url visible.
Anyway, fixed this now.
