### ISSUE TITLE
Desustorage hasn't been changed to Desuarchive yet

### ISSUE THREAD

**Issue by Flyingtoast** [Fiddlekins/SpookyX#12]
I hadn't noticed because I changed it myself when it happened, but Desu is still listed by its old domain name.
![anotha one](https://cloud.githubusercontent.com/assets/9301153/18604402/26df8692-7c4a-11e6-9ca2-5c0e386ad2db.PNG)

**Comment by Fiddlekins** [comment]
Whoops, accidentally took it out with the last commit, it's back in now.
