### ISSUE TITLE
[addition] overflow mode: hyphenate

### ISSUE THREAD

**Issue by filterop** [Fiddlekins/SpookyX#18]
Most print text use a hyphen for when a word is broken because of the end of a line. This helps differentiate whether the text had a space instead of a newline or space at that point. Might cause some issues for copying the text or for links though.

**Comment by Fiddlekins** [comment]
The current way it breaks words is by using a CSS property to handle it. Inserting hyphons where appropriate isn't possible to my knowledge without having to manually do it, which is not something I have the time nor inclination for.
