### ISSUE TITLE
Inline images behavior

### ISSUE THREAD

**Issue by josereyes53** [Fiddlekins/SpookyX#2]
This is not so much of a bug report, as I'm fairly certain that this is the intended behavior, but I think you should change how the inline images option works. Currently, it swaps every thumbnail on a thread for the actual file. This is a problem in threads that have a lot of images posted, like for example storytime threads on /co/, where various issues of comic books are posted image by image. The current behavior causes the page to load somewhat slowly and hog the browser a bit. Many times clicking on the images doesn't expand their size at all, I suspect because the wait for others to load. I propose (if possible), instead of loading EVERY image in a thread at once, to load the full image and place it inline only when the user clicks on the thumbnail. This way, only the clicked image will be loaded, and the rest will remain as thumbnails, avoiding having to wait for many images to load.

**Comment by Fiddlekins** [comment]
>This is not so much of a bug report
That's more than fine, this section is for all forms of feedback really.

>intended behavior
Yup.

>Many times clicking on the images doesn't expand their size at all, I suspect because the wait for others to load.
Clicking to expand an image that hasn't fully loaded doesn't do anything until the image finishes loading. On pageload it will start loading all images concurrently and as such they'll generally all finish at the same time.

>I propose [...]
I like it, that's now top of my to-do list. Not sure how soon I can add it though, just secured a new job and I'm moving location too so things are pretty busy for me right now.

Anyway, thanks for taking the time to suggest this.

**Comment by josereyes53** [comment]
Thank you for taking your time with this script. I had been looking for one that worked on archives for the longest time, and I must say you've done a great job.

**Comment by Fiddlekins** [comment]
Alright, v29.6 now has this feature.
