### ISSUE TITLE
Linkify urls?

### ISSUE THREAD

**Issue by Yoposoc** [Fiddlekins/SpookyX#4]
Is there a plan to linkify urls? For example, youtube links turn into their description.

**Comment by Fiddlekins** [comment]
It's been something I've always intended to do but have been holding off due to time constraints and the desire to do a proper job of it rather than doing a couple specific sites.

But YouTube is sufficiently ubiquitous that I may as well just add that here and now.
Enjoy v32.1

**Comment by Yoposoc** [comment]
thanks（＾ν＾）

**Comment by Yoposoc** [comment]
Not working on the OP post 
![5f4ebe1734 1](https://cloud.githubusercontent.com/assets/2718371/10080323/eea46222-62a3-11e5-9e9d-18a9986d4945.png)

**Comment by Fiddlekins** [comment]
Whoops, should be fixed now. Thanks for letting me know

**Comment by Yoposoc** [comment]
awesome
