### ISSUE TITLE
Inline reply expansion not working.

### ISSUE THREAD

**Issue by tallos** [Fiddlekins/SpookyX#5]
Inline reply expansion does not currently work on 4plebs or Desustorage, and possibly others.

It highlights the reply link clicked instead of expanding the reply inline, applies to both quotes and backquotes.

**Comment by Fiddlekins** [comment]
This seems to be working my end.
Can you give me more details to work with? (Browser, SpookyX version, are there any errors in the console log, etc)
At the risk of sounding condescending, have you checked that the option is enabled in the settings menu?

I'll probably look deeper into this at the weekend.

**Comment by tallos** [comment]
Chrome(both regular and SRWare Iron version), latest spookyX version, 3.10.109 Tampermonkey, inline replies box checked.

console error on post link/backlink click:
Uncaught TypeError: undefined is not a function VM2262:3621
(anonymous function) VM2262:3621
f.event.dispatch jquery.min.js:3
h.handle.i jquery.min.js:3

**Comment by Fiddlekins** [comment]
Welp, I got no idea why that's happening at first glance. I'm strapped for time midweek, so again, it'll probably be the weekend when I get to look into this.

As a sidenote: I very much doubt this will have any impact on the issue, but I seem to be running a v3.11 of Tampermonkey.

**Comment by Fiddlekins** [comment]
Okay, I'm afraid I've not been able to reproduce this or see what might be causing it in the first place. If it's convenient try to contact me for a real time conversation at #SpookyX on https://www.rizon.net/chat
