### ISSUE TITLE
Not working at arch.b4k.co

### ISSUE THREAD

**Issue by legovlas** [Fiddlekins/SpookyX#7]
Hello, I've recently noticed SpookyX isn't working on [https://arch.b4k.co/](https://arch.b4k.co/) as well as the http:// version.
I've looked into the console and I am getting [this error](http://i.imgur.com/QzSkm25.png). I am using Firefox v. 42, if that plays any role in this.

**Comment by Fiddlekins** [comment]
Yeah, Firefox a shit that can't handle mixed domain stylesheet manipulation or something, basically it was causing the code that tries to extract the site's spoilered text hover style for the view spoilers hovered all the time feature to fail.

The new v32.42 has addressed this issue.

**Comment by legovlas** [comment]
Works like a charm now, thank you very much.
